[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=1024"
  SECRETS_SCAN_OMIT_KEYS = "NUXT_PUBLIC_FIREBASE_API_KEY,NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NUXT_PUBLIC_FIREBASE_PROJECT_ID,NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NUXT_PUBLIC_FIREBASE_APP_ID,NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_i18n/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
