[build]
  command = "npm run build"
  publish = ".netlify/publish"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  SECRETS_SCAN_OMIT_KEYS = "NUXT_PUBLIC_FIREBASE_API_KEY,NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NUXT_PUBLIC_FIREBASE_PROJECT_ID,NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NUXT_PUBLIC_FIREBASE_APP_ID,NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID"

# Redirections SPA supprimées pour SSR

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_i18n/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
