[build]
  functions = "netlify/functions"
  publish = ".output/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.lh]
  timeout = 300
  memory = 3008

[build.environment]
  NODE_VERSION = "18"

# Redirections SPA supprimées pour SSR

# EN-TÊTES DE SÉCURITÉ TEMPORAIREMENT DÉSACTIVÉS POUR FIREBASE
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "SAMEORIGIN"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"

# [[headers]]
#   for = "/login"
#   [headers.values]
#     Cross-Origin-Opener-Policy = "same-origin-allow-popups"

# [[headers]]
#   for = "/__/auth/*"
#   [headers.values]
#     Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_i18n/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
