[build]
  command = "npm run build:netlify"
  publish = ".netlify/publish"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

# Configuration pour le mode SPA (SSR désactivé)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirections spécifiques pour les assets
[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

# Headers de sécurité et de performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers pour les assets statiques
[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les images et autres assets
[[headers]]
  for = "*.{jpg,jpeg,png,gif,ico,svg,webp}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des fonctions (si nécessaire)
[functions]
  node_bundler = "esbuild"
