[build]
  command = "echo 'Using local build artifacts'"
  publish = ".netlify/publish"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.19.4"
  NODE_OPTIONS = "--max-old-space-size=8192"
  SECRETS_SCAN_OMIT_KEYS = "NUXT_PUBLIC_FIREBASE_API_KEY,NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NUXT_PUBLIC_FIREBASE_PROJECT_ID,NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NUXT_PUBLIC_FIREBASE_APP_ID,NUXT_PUBLIC_FIREBASE_MEASUREMENT_ID"

# Redirections SPA supprimées pour SSR

# EN-TÊTES DE SÉCURITÉ TEMPORAIREMENT DÉSACTIVÉS POUR FIREBASE
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "SAMEORIGIN"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"

# [[headers]]
#   for = "/login"
#   [headers.values]
#     Cross-Origin-Opener-Policy = "same-origin-allow-popups"

# [[headers]]
#   for = "/__/auth/*"
#   [headers.values]
#     Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_i18n/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
